In [9]:
import pandas as pd

In [14]:
a=pd.read_csv("/content/train.csv")

In [15]:
print(a)

      battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
...             ...   ...          ...       ...  ..     ...         ...   
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  \
0       

In [16]:
xtrain=a.drop(columns=['price_range'])
print(xtrain)

      battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
...             ...   ...          ...       ...  ..     ...         ...   
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  pc  px_height  px_width   ram  sc_h  sc_w  \
0       0

In [17]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler(feature_range=(0,1))
xtrain_norm=scaler.fit_transform(xtrain)

In [18]:
print(xtrain_norm)

[[0.22778891 0.         0.68       ... 0.         0.         1.        ]
 [0.34736139 1.         0.         ... 1.         1.         0.        ]
 [0.04141617 1.         0.         ... 1.         1.         0.        ]
 ...
 [0.94188377 0.         0.16       ... 1.         1.         0.        ]
 [0.6753507  0.         0.16       ... 1.         1.         1.        ]
 [0.00601202 1.         0.6        ... 1.         1.         1.        ]]


In [19]:
from sklearn.model_selection import train_test_split

In [20]:
y=a['price_range']

In [21]:
x_train,x_test,y_train,y_test=train_test_split(xtrain_norm,y,test_size=0.3)

In [22]:
print(x_train)

[[0.82899132 1.         0.         ... 1.         1.         0.        ]
 [0.03941216 0.         0.         ... 1.         1.         0.        ]
 [0.52705411 1.         0.36       ... 1.         0.         0.        ]
 ...
 [0.41282565 0.         0.         ... 1.         0.         0.        ]
 [0.38476954 1.         0.48       ... 1.         0.         0.        ]
 [0.57114228 1.         0.         ... 1.         1.         1.        ]]


In [23]:
print(x_test)

[[0.63193053 1.         0.8        ... 0.         0.         0.        ]
 [0.25851703 0.         0.84       ... 1.         0.         0.        ]
 [0.49298597 0.         0.28       ... 1.         0.         1.        ]
 ...
 [0.14161657 0.         0.44       ... 1.         0.         0.        ]
 [0.74348697 0.         0.56       ... 1.         0.         0.        ]
 [0.76619906 1.         0.         ... 1.         0.         1.        ]]


In [24]:
b=pd.read_csv('/content/heart.csv')

In [25]:
print(b)

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2     

In [26]:
k=b.drop(columns=['target'])
print(k)

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  
0        0   0     1  
1        0   0     2  
2        2   0    

In [27]:
l=b['target']

In [28]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler(feature_range=(0,1))
ktrain_norm=scaler.fit_transform(k)

In [29]:
print(ktrain_norm)

[[0.70833333 1.         1.         ... 0.         0.         0.33333333]
 [0.16666667 1.         0.66666667 ... 0.         0.         0.66666667]
 [0.25       0.         0.33333333 ... 1.         0.         0.66666667]
 ...
 [0.8125     1.         0.         ... 0.5        0.5        1.        ]
 [0.58333333 1.         0.         ... 0.5        0.25       1.        ]
 [0.58333333 0.         0.33333333 ... 0.5        0.25       0.66666667]]


In [30]:
from sklearn.model_selection import train_test_split

In [31]:
k_train,k_test,l_train,l_test=train_test_split(ktrain_norm,l,test_size=0.3)

In [32]:
print(k_train)

[[0.77083333 1.         0.33333333 ... 0.5        0.75       0.33333333]
 [0.5625     1.         0.33333333 ... 1.         0.         1.        ]
 [0.52083333 1.         0.66666667 ... 1.         0.         1.        ]
 ...
 [0.6875     1.         0.66666667 ... 0.5        0.75       1.        ]
 [0.54166667 0.         0.33333333 ... 1.         0.         0.66666667]
 [0.625      1.         0.         ... 0.5        0.         1.        ]]


In [33]:
print(k_test)

[[0.52083333 1.         0.         ... 0.5        0.25       0.66666667]
 [0.29166667 0.         0.         ... 0.5        0.         1.        ]
 [0.875      0.         0.66666667 ... 1.         0.25       0.66666667]
 ...
 [0.375      1.         0.66666667 ... 1.         0.         0.66666667]
 [0.58333333 1.         0.         ... 1.         0.         1.        ]
 [0.77083333 1.         0.         ... 1.         0.25       0.66666667]]


In [34]:
import numpy as np

In [35]:
x1=b['age']
x2=b['sex']
x3=b['cp']
x4=b['trestbps']
x5=b['chol']
x6=b['fbs']
x7=b['restecg']
x8=b['thalach']
x9=b['exang']
x10=b['oldpeak']
x11=b['slope']
x12=b['ca']
x13=b['thal']
y_p=[]

In [37]:
def perceptron(w1,w2,w3,w4,w5,w6,w7,w8,w9,w10,w11,w12,w13,b):
  for i in range(len(x1)):
    z=x1[i]*w1+x2[i]*w2+x3[i]*w3+x4[i]*w4+x5[i]*w5+x6[i]*w6+x7[i]*w7+x8[i]*w8+x9[i]*w9+x10[i]*w10+x11[i]*w11+x12[i]*w12+x13[i]*w13+b
    s=1/1+np.exp(-z)
    if (s>=0.5):
      y_p.append(1)
    else:
      y_p.append(0)
  return y_p

print(perceptron(1,2,3,1,2,3,1,2,3,1,2,3,1,10))

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
